.github:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
  excludeFiles:
    - workflows
    - workflows-v2
    - nodejs.version

.github/workflows-v2:
  projects:
    - NextJs/NextJs15
    - node
  asName: workflows
  excludeFiles:
    - ci.yml

.github/nodejs.version:
  projects:
    - startetNpmPackage/node
    - node

.github/workflows:
  projects:
    - startetNpmPackage/node

.husky:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
  excludeFiles:
    - lint-staged-with-style.config.json
    - lint-staged.config.json

.husky/lint-staged.config.json:
  projects:
    - startetNpmPackage/node
    - node

.husky/lint-staged-with-style.config.json:
  projects:
    - NextJs/NextJs15
  asName: lint-staged.config.json

.vscode:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

"[next]":
  projects:
    - NextJs/NextJs15
  copyToRoot: true

'[node]':
  projects:
    - startetNpmPackage/node
    - node
  copyToRoot: true

"@types":
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

docs:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
  excludeFiles:
    - npm.png
    - "[web]"
    - "[npm]"

docs/[web]/HowToAutoDeploy.md:
  projects:
    - NextJs/NextJs15
  asName: ../HowToAutoDeploy.md

docs/[npm]/HowToAutoDeploy.md:
  projects:
    - startetNpmPackage/node
    - node
  asName: ../HowToAutoDeploy.md

tools:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
  excludeFiles:
    - transform-browser-list
    - addDependency.js
    - addModuleType.js

tools/transform-browser-list:
  projects:
    - NextJs/NextJs15

tools/addDependency.js:
  projects:
    - startetNpmPackage/node
    - node

tools/addModuleType.js:
  projects:
    - startetNpmPackage/node
    - node

.commitlintrc.js:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.cursorignore:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.editorconfig:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.gitattributes:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.npmrc:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.nvmrc:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.prettierignore:
  - startetNpmPackage/node
  - node

.quokka:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

.releaserc.js:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

LICENSE:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node

prettier.config.js:
  - startetNpmPackage/node
  - node
