.github:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule
  excludeFiles:
    - workflows

.github/workflows:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule
  excludeFiles:
    - ci.yml

.husky:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule
  excludeFiles:
    - lint-staged-with-style.config.json
    - lint-staged.config.json

.husky/lint-staged.config.json:
  projects:
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule

.husky/lint-staged-with-style.config.json:
  projects:
    - NextJs/NextJs15
  asName: lint-staged.config.json

.vscode:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

"[next]":
  projects:
    - NextJs/NextJs15
  copyToRoot: true

'[node]':
  projects:
    - startetNpmPackage/node
    - node
  copyToRoot: true

'[nestjs]':
  projects:
    - nestjs
    - nestjsModule
  copyToRoot: true

docs:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule
  excludeFiles:
    - npm.png
    - "[web]"
    - "[npm]"

docs/[web]:
  projects:
    - NextJs/NextJs15
  asName: ../docs


docs/[npm]/HowToAutoDeploy.md:
  projects:
    - startetNpmPackage/node
    - node
    - nestjsModule
  asName: ../HowToAutoDeploy.md

tools:
  projects:
    - NextJs/NextJs15
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule
  excludeFiles:
    - transform-browser-list
    - addDependency.js
    - addModuleType.js

tools/transform-browser-list:
  projects:
    - NextJs/NextJs15

tools/addDependency.js:
  projects:
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule

tools/addModuleType.js:
  projects:
    - startetNpmPackage/node
    - node
    - nestjs
    - nestjsModule

.commitlintrc.js:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.cursorignore:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.editorconfig:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.gitattributes:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.npmrc:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.nvmrc:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.prettierignore:
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.quokka:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

.releaserc.js:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

LICENSE:
  - NextJs/NextJs15
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule

prettier.config.js:
  - startetNpmPackage/node
  - node
  - nestjs
  - nestjsModule
