{
  "name": "placeholder-repo-name",
  "version": "0.0.0-development",
  "description": "{{A template for creating ...}}",
  "private": true,
  "scripts": {
    "ℹ️ info:Development": "ℹ️",
    "dev": "npm run next",
    "dev:storybook": "run-p dev storybook",
    "dev:tunnel": "run-p ngrok:auth dev ngrok",
    "ℹ️ info:Production": "ℹ️",
    "build": "cross-env NODE_ENV=production next build",
    "build:start": "cross-env NODE_ENV=production run-s build:prod next:start",
    "build:analyze": "cross-env ANALYZE=true run-s build",
    "build:prod": "run-s build build:postbuild",
    "build:postbuild": "next-sitemap",
    "ℹ️ info:Testing": "ℹ️",
    "test": "run-p test:*",
    "test:unit": "node --experimental-vm-modules node_modules/jest/bin/jest.js --runInBand --passWithNoTests 'src/**/*.test.ts'",
    "test:components": "node --experimental-vm-modules node_modules/jest/bin/jest.js --runInBand --passWithNoTests 'src/**/*.test.tsx'",
    "test:snapshot": "cross-env TEST_WITH_SNAPSHOTS=true node --experimental-vm-modules node_modules/jest/bin/jest.js --silent --passWithNoTests --updateSnapshot",
    "test:unit:watch": "node --experimental-vm-modules node_modules/jest/bin/jest.js --watch --passWithNoTests",
    "test:smoke": "yarn playwright:install && yarn test-storybook",
    "test:e2e": "playwright test",
    "test:e2e:ui": "playwright test --ui",
    "test:changed:unit": "yarn test:unit --onlyChanged",
    "test:changed:components": "yarn test:components --onlyChanged ",
    "ℹ️ info:Linting": "ℹ️",
    "lint": "cross-env sh -c '(run-s lint:check 2>/dev/null) || (run-s lint:fix && run-s lint:check)'",
    "lint:check": "run-p lint:typescript:check lint:prettier:check lint:eslint:check lint:style:check",
    "lint:fix": "run-p lint:prettier:fix lint:eslint:fix lint:style:fix",
    "lint:prettier:check": "prettier --check --cache './src/**/*.{js,jsx,ts,tsx,md,mdx,json}'",
    "lint:prettier:fix": "prettier --write --cache './src/**/*.{js,jsx,ts,tsx,md,mdx,json}'",
    "lint:eslint:check": "eslint --no-error-on-unmatched-pattern --cache './src/**/*.+(js|jsx|ts|tsx)' --max-warnings 0 --config eslint.config.mjs",
    "lint:eslint:check:strict": "eslint --no-error-on-unmatched-pattern --cache './src/**/*.+(js|jsx|ts|tsx)' --max-warnings 0 --config eslint.config.strict.mjs",
    "lint:eslint:fix": "eslint --no-error-on-unmatched-pattern --cache './src/**/*.+(js|jsx|ts|tsx)' --fix --config eslint.config.strict.mjs",
    "lint:style:check": "stylelint './src/**/*.{css,scss,sass}' --cache --config stylelint.config.js",
    "lint:style:fix": "stylelint './src/**/*.{css,scss,sass}' --cache --fix --config stylelint.config.js",
    "lint:typescript:check": "tsc --noEmit",
    "ℹ️ info:Quality": "ℹ️",
    "quality:knip": "knip",
    "quality:coverage": "yarn test:unit --coverage --coverageDirectory=./reports/coverage",
    "quality:report": "//TODO echo 'preparing report...'",
    "copy:assets": "//TODO coppy assets'",
    "quality:coupling:graph": "yarn mkdir:reports && npx madge ./src --extensions js,jsx,ts,tsx,md,mdx,css --basedir ./src --exclude '.next|tailwind.config.js|reset.d.ts|prettier.config.js|postcss.config.js|playwright.config.ts|next.config.js|next-env.d.ts|instrumentation.ts|e2e/|README.md|.storybook/|.eslintrc.js' --image reports/coupling.svg --image reports/coupling.png",
    "quality:coupling:json": "yarn mkdir:reports && npx madge ./src --extensions js,jsx,ts,tsx,md,mdx,css --basedir ./src --json --exclude '.next|tailwind.config.js|reset.d.ts|prettier.config.js|postcss.config.js|playwright.config.ts|next.config.js|next-env.d.ts|instrumentation.ts|e2e/|README.md|.storybook/|.eslintrc.js' > reports/coupling.json",
    "ℹ️ info:Git": "ℹ️",
    "husky:commit-msg": "commitlint --edit ${HUSKY_GIT_PARAMS:-$1}",
    "husky:pre-commit": "lint-staged -c ./.husky/lint-staged.config.json",
    "husky:pre-push": "run-p lint:check test:smoke",
    "husky:prepare-commit-msg": "exec < /dev/tty && yarn commit --hook || true",
    "commit": "czg",
    "prepare": "husky",
    "ℹ️ info:Tools": "ℹ️",
    "update-vscode-colors": "node tools/updateVSCodeColors.js",
    "mkdir:reports": "mkdir -p reports",
    "next": "next dev --turbo",
    "next:start": "next start",
    "ngrok": "ngrok http 3000",
    "ngrok:auth": "node tools/ngrok-auth.js",
    "customize": "tsx tools/customize/customize.ts",
    "playwright:install": "yarn playwright install --with-deps",
    "update-template": "s-update --remoteRepository='https://github.com/SebastianWesolowski/s-template/tree/dev/templates/NextJs/NextJs15'",
    "update-template:build": "s-build --remoteRepository='https://github.com/SebastianWesolowski/s-template/tree/dev/templates/NextJs/NextJs15'",
    "storybook": "storybook dev -p 6006",
    "storybook:build": "storybook build",
    "postinstall": "npx patch-package -y"
  },
  "dependencies": {
    "@fontsource/inter": "^5.1.1",
    "@fontsource/lexend": "^5.1.2",
    "@headlessui/react": "^2.2.0",
    "@next/bundle-analyzer": "^15.1.6",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-form": "^0.0.3",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-scroll-area": "^1.0.5",
    "@radix-ui/react-select": "2.0.0",
    "@radix-ui/react-slider": "^1.1.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toggle-group": "^1.0.4",
    "@radix-ui/react-tooltip": "^1.0.7",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/commit-analyzer": "^13.0.1",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/github": "^11.0.1",
    "@semantic-release/npm": "^12.0.1",
    "@semantic-release/release-notes-generator": "^14.0.3",
    "@storybook/addon-styling-webpack": "^1.0.1",
    "@storybook/addon-themes": "^8.5.4",
    "@t3-oss/env-nextjs": "^0.10.1",
    "class-variance-authority": "^0.7.0",
    "lodash": "^4.17.21",
    "next": "^15.1.7",
    "next-sitemap": "^4.2.3",
    "next-themes": "^0.4.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-hotjar": "^6.3.1",
    "react-icons": "^5.4.0",
    "tailwind-merge": "^2.3.0",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@babel/core": "^7.23.3",
    "@babel/plugin-syntax-flow": "^7.23.3",
    "@babel/plugin-transform-optional-chaining": "^7.23.4",
    "@babel/plugin-transform-react-jsx": "^7.23.4",
    "@commitlint/cli": "^19.7.1",
    "@commitlint/config-conventional": "^19.7.1",
    "@ef-carbon/tspm": "^2.2.5",
    "@eslint/eslintrc": "^3",
    "@jest/globals": "^29.7.0",
    "@next/eslint-plugin-next": "15.1.6",
    "@playwright/test": "^1.40.0",
    "@ryansonshine/commitizen": "^4.2.8",
    "@semantic-release/exec": "^7.0.3",
    "@storybook/addon-a11y": "^8.5.4",
    "@storybook/addon-controls": "^8.5.4",
    "@storybook/addon-docs": "^8.5.4",
    "@storybook/addon-essentials": "^8.5.4",
    "@storybook/addon-interactions": "^8.5.4",
    "@storybook/addon-links": "^8.5.4",
    "@storybook/addon-outline": "^8.5.4",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/blocks": "^8.5.4",
    "@storybook/nextjs": "^8.5.4",
    "@storybook/react": "^8.5.4",
    "@storybook/test": "^8.5.4",
    "@storybook/test-runner": "^0.21.0",
    "@tailwindcss/postcss": "^4.0.0",
    "@testing-library/jest-dom": "^6.1.4",
    "@testing-library/react": "^14.1.2",
    "@total-typescript/ts-reset": "^0.5.1",
    "@trivago/prettier-plugin-sort-imports": "^5.2.2",
    "@types/jest": "^29.5.10",
    "@types/node": "^22.13.1",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@typescript-eslint/eslint-plugin": "8.21.0",
    "@typescript-eslint/parser": "^5.54.1",
    "all-contributors-cli": "^6.26.1",
    "autoprefixer": "^10.4.20",
    "commitizen": "^4.3.1",
    "concurrently": "^9.1.2",
    "conventional-changelog-conventionalcommits": "^8.0.0",
    "critters": "^0.0.20",
    "cross-env": "^7.0.3",
    "cssnano": "^7.0.6",
    "cssnano-preset-advanced": "^7.0.6",
    "czg": "^1.11.0",
    "eslint": "^9",
    "eslint-config-next": "15.1.7",
    "eslint-config-prettier": "^10.0.1",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-next-on-pages": "^1.13.7",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react-hooks": "^5.1.0",
    "eslint-plugin-storybook": "^0.11.2",
    "eslint-plugin-tailwindcss": "^3.18.0",
    "eslint-plugin-unused-imports": "^4.1.4",
    "fetch-mock": "^9.11.0",
    "fork-ts-checker-webpack-plugin": "^9.0.2",
    "gzip-size": "6.0.0",
    "handlebars-helpers": "^0.10.0",
    "husky": "^9.0.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "knip": "^5.44.0",
    "lint-staged": "^13.2.1",
    "madge": "^8.0.0",
    "mkdirp": "^3.0.1",
    "ngrok": "^5.0.0-beta.2",
    "npm-run-all": "^4.1.5",
    "patch-package": "^8.0.0",
    "playwright": "^1.50.1",
    "postcss": "^8.5.2",
    "postcss-discard-comments": "^7.0.3",
    "postcss-import": "^16.1.0",
    "postcss-loader": "^8.1.1",
    "postcss-preset-env": "^10.1.3",
    "postinstall-postinstall": "^2.1.0",
    "prettier": "^3.5.0",
    "prettier-plugin-tailwindcss": "^0.6.11",
    "s-prettier": "^1.1.0",
    "s-update-manager": "^1.0.0-dev.48",
    "sass": "^1.84.0",
    "sass-loader": "^16.0.4",
    "semantic-release": "^24.2.2",
    "storybook": "^8.5.4",
    "style-loader": "^4.0.0",
    "stylelint": "^16.14.1",
    "stylelint-config-rational-order-fix": "^0.1.9",
    "stylelint-config-standard": "^37.0.0",
    "stylelint-config-standard-scss": "^14.0.0",
    "stylelint-config-tailwindcss": "^1.0.0",
    "stylelint-no-unresolved-module": "^2.3.0",
    "stylelint-no-unsupported-browser-features": "^8.0.4",
    "stylelint-order": "^6.0.4",
    "stylelint-scss": "^6.11.0",
    "tailwindcss": "^4.0.0",
    "ts-jest": "^29.1.1",
    "tsc": "^2.0.4",
    "tsx": "^4.19.2",
    "typed-query-selector": "^2.12.0",
    "typescript": "^5.7.3",
    "typescript-eslint": "^8.21.0",
    "webpack": "^5.97.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/{{PLACEHOLDER_GITHUB_USER}}/{{PLACEHOLDER_REPO_NAME}}.git"
  },
  "license": "MIT",
  "author": {
    "name": "{{PLACEHOLDER_FULL_NAME}}",
    "email": "{{PLACEHOLDER_GITHUB_USER}}@users.noreply.github.com",
    "url": "https://github.com/{{PLACEHOLDER_GITHUB_USER}}"
  },
  "engines": {
    "node": ">=0.0.0"
  },
  "bugs": {
    "url": "https://github.com/{{PLACEHOLDER_GITHUB_USER}}/{{PLACEHOLDER_REPO_NAME}}/issues"
  },
  "homepage": "https://github.com/{{PLACEHOLDER_GITHUB_USER}}/{{PLACEHOLDER_REPO_NAME}}#readme",
  "config": {
    "commitizen": {
      "path": "node_modules/cz-git"
    },
    "issueTag": "SC"
  }
}
