name: Auto-merge main to dev

on:
  workflow_run:
    workflows: ["Release"] # Replace with your semantic-release workflow name
    types:
      - completed
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge main to dev
        run: |
          git checkout dev
          git pull
          git merge --no-ff origin/main -m "chore: auto-merge main into dev [skip ci]"
          git push origin dev
